### ISSUE TITLE
Name should be normalised

### ISSUE THREAD

**Issue by annejan** [noprotocol/generator-np-laravel#2]
Since the name is used in the `package.json` it should be "normalised" in some way.

```
npm ERR! Invalid name: "Some project name with spaces"
```

**Comment by Hyra** [comment]
Same is true for the database name

**Comment by verschuur** [comment]
The project name is now slugged using hyphens, and the database is slugged using underscores.

See ec250268fb048dcdbc6d10ed88e7fe8c3d3d6e8d
